services:
  solterm:
    image: ghcr.io/lukegus/solterm:latest
    container_name: solterm
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - solterm-data:/app/data
    environment:
      PORT: "8080"

volumes:
  solterm-data:
    driver: local 